[project]
name = "student_repo_analyzer"
version = "0.1.0"
description = "Python bindings to Practice Grading application"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Kirill K. Smirnov", email = "kirill.k.smirnov@gmail.com"},
]
dependencies = [
    "python-dotenv",
    "requests",
    "python-dateutil",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "mypy",
    "pylint",
    "types-python-dateutil",
]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "line-too-long",
    "broad-exception-caught",
    "invalid-name",
]

[tool.black]
line-length = 120
